### ISSUE TITLE
не работает в seamonkey 2.53

### ISSUE THREAD

**Issue by slavb18** [iconicompany/cloudtreasury#44]
Вкладка расчеты (https://demo.iconicompany.ru/cloudtreasury/calculations)
 в seamonkey 2.53 выдает ошибку
Application error: a client-side exception has occurred (see the browser console for more information).

Повторить:

скачать tar файл https://www.seamonkey-project.org/releases/, распаковать в /opt, запустить /opt/seamonkey/seamonkey-bin

проверить на ветке `master`, в режиме `npm run build` + `npm start`

**Comment by pivotdude** [comment]
Заменил на `  let height;
  let width;
  try {
    var _getComputedStyle = getComputedStyle(target, '::-webkit-scrollbar');
      width = _getComputedStyle.width;
      height = _getComputedStyle.height;
      console.log(height, width)
  } catch (error) { // don`t support
    width = 'auto'
    height = 'auto'
  }
  return {
    width: ensureSize(width),
    height: ensureSize(height)
  };` ошибка исправилась

**Comment by pivotdude** [comment]
Можно patch-package установить и патч сделать, чтобы при установке всех пакетов, патч автоматический накатывался на либу.
